void imprimirTelaInicial();
void imprimirMenuPrincipal();
int escolher();
void emDesenvolvimento();
void imprimirEscolhaInvalida();
void imprimirSubMenuJogar();
void imprimirJogar1x1();
void imprimirJogar1xIA();
void imprimirJogoIniciado();
void imprimirJogadorInicial(int);
void imprimirPeca(PECA [], int);
void imprimirPecaMesa(PECA_MESA [], int);
void imprimirMesa(PECA_MESA [], CONTADOR *);
void imprimirTurno(int);
void imprimrVezJogador(int);
void imprimirMao(PECA [], int, CONTADOR *);
void imprimirMenuJogando(PECA [], int);
void imprimirSelecionarPeca(CONTADOR *, int);
void imprimirJogadaInvalida();
void imprimirJogadaFeita();
void imprimirCompraIndisponivel();
void imprimirPassarVez();
void imprimirHaJogadaDisponivel();
void imprimirMenuCompra(PECA [], CONTADOR *);
void imprimirVoltarMenu();
void imprimirSairdoPrograma();